spring:
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: server
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  profiles:
    include: mybatis-local

server:
  port: 8090
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t \"%r\" %s %b @@ANALYSIS@@ %U=%D"
      directory: logs/
    basedir: ./
    max-threads: 512
    min-spare-threads: 32
    connection-timeout: 2M

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error