server:
  port: 8090
  servlet:
    context-path: /example

spring:
  application:
    name: vegeta
  vegeta:
    thread-pool:
      server-addr: http://localhost:8080
      namespace: prescription
      app-id: ${spring.application.name}

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
  config: classpath:logback-spring.xml

