spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vegeta?serverTimezone=Asia/Shanghai
    username: root
    password: wdfzq1957
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initial-size: 10
      max-wait: 200
      max-idle: 100
      mac-active: 100
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: select 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 600000
      num-tests-per-eviction-run: 10

logging:
  level:
    xbk:
      dao:
        mapper:
          debug